### ISSUE TITLE
How to send MIDI to  DAW or MIDI Support Web?

### ISSUE THREAD

**Issue by mommocmoc** [Deeplocal/fruit-genie#6]
I want to know how to send MIDI to DAW or MIDI Support Web.
Is there any reference or example node app sending MIDI Signal to DAW/MIDI Support Web?

I'm not a developer, and don't know exactly how the code of fruit-genie working.(Especially Nodejs)

However, I really want to make something fun for students using fruit-genie. 

Please give some help.

Thank you.

**Comment by pegula** [comment]
I think that @notwaldorf has played with this. 

https://github.com/notwaldorf/teensy-midi

**Comment by notwaldorf** [comment]
Yup, if you look at my repo, I basically stripped out all the piano-genie work that was done in this node app, and changed it to emit MIDI events every time a touch is registered. Let me know if you have any problems setting it up!

**Comment by mommocmoc** [comment]
Thanks everybody! I'll try and close this issue!

**Comment by mommocmoc** [comment]
@notwaldorf 
I can't follow up from this step. I couldn't find the gear button on https://piano-genie.glitch.me/ 😢 
2. After you dismiss the splash, click on the **gear button**

**Comment by pegula** [comment]
It looks like the gear button will only appear if the browser detects a midi device.  Is your teensy plugged in?

**Comment by notwaldorf** [comment]
Yup, make sure your Teensy is plugged in, and the node process is started (and you are things being logged in the console when you press the fruit). If all of this works, piano-genie should show the gear.

Also i didn’t mention this but it might not have been obvious to everyone: you should load piano-genie on the same computer the Teensy is connected to.

**Comment by mommocmoc** [comment]
I didn't check the USB type of teensy board. I changed it to MIDI and I can see the gear!
Thanks everyone!

**Comment by mommocmoc** [comment]
I don't know why piano genie can't read midi note from app.js. It may be OS problem. 😢 

As you know, Teensy 3.1 & 3.2 has touch pins and can be used as keyboard, so I just programed teensy touch pin as a keypad  for piano-genie. This is proper for me. 
If having interest, check my repo : https://github.com/mommocmoc/teensy-keypad
Thanks again.
